/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RoadWatchBadge } from "./RoadWatchBadge";
export type { RoadWatchManagerFHE } from "./RoadWatchManagerFHE";
