/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RoadWatchManagerFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "badgeContract"
      | "claimBadge"
      | "claimedBadgeBitmap"
      | "confidentialProtocolId"
      | "getRecord"
      | "getRecordCount"
      | "getRecordsByReporter"
      | "getSeverity"
      | "getUserBadgeState"
      | "getUserContributionCount"
      | "isEligibleForLevel"
      | "lastSubmitAt"
      | "minIntervalSec"
      | "nextRecordId"
      | "owner"
      | "renounceOwnership"
      | "requestView"
      | "setBadgeContract"
      | "setMinIntervalSec"
      | "submitRecord"
      | "transferOwnership"
      | "updateSeverity"
      | "viewCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RecordSubmitted"
      | "RecordViewed"
      | "SeverityUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "badgeContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimBadge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedBadgeBitmap",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordsByReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSeverity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBadgeState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserContributionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleForLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastSubmitAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minIntervalSec",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextRecordId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestView",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBadgeContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinIntervalSec",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRecord",
    values: [string, string, string, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSeverity",
    values: [BigNumberish, BytesLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "viewCount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "badgeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimBadge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimedBadgeBitmap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordsByReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSeverity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBadgeState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserContributionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleForLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastSubmitAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minIntervalSec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRecordId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBadgeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinIntervalSec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSeverity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "viewCount", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordSubmittedEvent {
  export type InputTuple = [recordId: BigNumberish, reporter: AddressLike];
  export type OutputTuple = [recordId: bigint, reporter: string];
  export interface OutputObject {
    recordId: bigint;
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordViewedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    viewer: AddressLike,
    newCount: BigNumberish
  ];
  export type OutputTuple = [
    recordId: bigint,
    viewer: string,
    newCount: bigint
  ];
  export interface OutputObject {
    recordId: bigint;
    viewer: string;
    newCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeverityUpdatedEvent {
  export type InputTuple = [recordId: BigNumberish];
  export type OutputTuple = [recordId: bigint];
  export interface OutputObject {
    recordId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RoadWatchManagerFHE extends BaseContract {
  connect(runner?: ContractRunner | null): RoadWatchManagerFHE;
  waitForDeployment(): Promise<this>;

  interface: RoadWatchManagerFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  badgeContract: TypedContractMethod<[], [string], "view">;

  claimBadge: TypedContractMethod<[level: BigNumberish], [void], "nonpayable">;

  claimedBadgeBitmap: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getRecord: TypedContractMethod<
    [recordId: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint] & {
        id: bigint;
        reporter: string;
        description: string;
        city: string;
        category: string;
        imageCID: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getRecordCount: TypedContractMethod<[], [bigint], "view">;

  getRecordsByReporter: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  getSeverity: TypedContractMethod<[recordId: BigNumberish], [string], "view">;

  getUserBadgeState: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        claimedBitmap: bigint;
        maxEligibleLevel: bigint;
        contributionCount: bigint;
      }
    ],
    "view"
  >;

  getUserContributionCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  isEligibleForLevel: TypedContractMethod<
    [user: AddressLike, level: BigNumberish],
    [boolean],
    "view"
  >;

  lastSubmitAt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  minIntervalSec: TypedContractMethod<[], [bigint], "view">;

  nextRecordId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestView: TypedContractMethod<
    [recordId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  setBadgeContract: TypedContractMethod<
    [badge: AddressLike],
    [void],
    "nonpayable"
  >;

  setMinIntervalSec: TypedContractMethod<
    [v: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitRecord: TypedContractMethod<
    [
      description: string,
      city: string,
      category: string,
      imageCID: string,
      severityExt: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSeverity: TypedContractMethod<
    [
      recordId: BigNumberish,
      deltaExt: BytesLike,
      inputProof: BytesLike,
      add: boolean
    ],
    [void],
    "nonpayable"
  >;

  viewCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "badgeContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimBadge"
  ): TypedContractMethod<[level: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedBadgeBitmap"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint] & {
        id: bigint;
        reporter: string;
        description: string;
        city: string;
        category: string;
        imageCID: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecordsByReporter"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSeverity"
  ): TypedContractMethod<[recordId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getUserBadgeState"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        claimedBitmap: bigint;
        maxEligibleLevel: bigint;
        contributionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserContributionCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isEligibleForLevel"
  ): TypedContractMethod<
    [user: AddressLike, level: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastSubmitAt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "minIntervalSec"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextRecordId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestView"
  ): TypedContractMethod<[recordId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setBadgeContract"
  ): TypedContractMethod<[badge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinIntervalSec"
  ): TypedContractMethod<[v: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitRecord"
  ): TypedContractMethod<
    [
      description: string,
      city: string,
      category: string,
      imageCID: string,
      severityExt: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSeverity"
  ): TypedContractMethod<
    [
      recordId: BigNumberish,
      deltaExt: BytesLike,
      inputProof: BytesLike,
      add: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "viewCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RecordSubmitted"
  ): TypedContractEvent<
    RecordSubmittedEvent.InputTuple,
    RecordSubmittedEvent.OutputTuple,
    RecordSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RecordViewed"
  ): TypedContractEvent<
    RecordViewedEvent.InputTuple,
    RecordViewedEvent.OutputTuple,
    RecordViewedEvent.OutputObject
  >;
  getEvent(
    key: "SeverityUpdated"
  ): TypedContractEvent<
    SeverityUpdatedEvent.InputTuple,
    SeverityUpdatedEvent.OutputTuple,
    SeverityUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RecordSubmitted(uint256,address)": TypedContractEvent<
      RecordSubmittedEvent.InputTuple,
      RecordSubmittedEvent.OutputTuple,
      RecordSubmittedEvent.OutputObject
    >;
    RecordSubmitted: TypedContractEvent<
      RecordSubmittedEvent.InputTuple,
      RecordSubmittedEvent.OutputTuple,
      RecordSubmittedEvent.OutputObject
    >;

    "RecordViewed(uint256,address,uint256)": TypedContractEvent<
      RecordViewedEvent.InputTuple,
      RecordViewedEvent.OutputTuple,
      RecordViewedEvent.OutputObject
    >;
    RecordViewed: TypedContractEvent<
      RecordViewedEvent.InputTuple,
      RecordViewedEvent.OutputTuple,
      RecordViewedEvent.OutputObject
    >;

    "SeverityUpdated(uint256)": TypedContractEvent<
      SeverityUpdatedEvent.InputTuple,
      SeverityUpdatedEvent.OutputTuple,
      SeverityUpdatedEvent.OutputObject
    >;
    SeverityUpdated: TypedContractEvent<
      SeverityUpdatedEvent.InputTuple,
      SeverityUpdatedEvent.OutputTuple,
      SeverityUpdatedEvent.OutputObject
    >;
  };
}
